# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_Calculadora.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(11, 40, 591, 511))
        self.frame.setStyleSheet("background-color: rgb(192, 191, 188);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.fm_botones = QtWidgets.QFrame(self.frame)
        self.fm_botones.setGeometry(QtCore.QRect(20, 150, 561, 351))
        self.fm_botones.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fm_botones.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fm_botones.setObjectName("fm_botones")
        self.btnDiv = QtWidgets.QPushButton(self.fm_botones)
        self.btnDiv.setGeometry(QtCore.QRect(350, 280, 88, 51))
        self.btnDiv.setStyleSheet("background-color: rgb(224, 27, 36);")
        self.btnDiv.setObjectName("btnDiv")
        self.btnPot = QtWidgets.QPushButton(self.fm_botones)
        self.btnPot.setGeometry(QtCore.QRect(460, 280, 88, 51))
        self.btnPot.setStyleSheet("background-color: rgb(145, 65, 172);\n"
"color: rgb(246, 245, 244);\n"
"")
        self.btnPot.setObjectName("btnPot")
        self.btn2 = QtWidgets.QPushButton(self.fm_botones)
        self.btn2.setGeometry(QtCore.QRect(130, 200, 88, 51))
        self.btn2.setStyleSheet("background-color: rgb(28, 113, 216);\n"
"color: rgb(246, 245, 244);\n"
"\n"
"")
        self.btn2.setObjectName("btn2")
        self.btn9 = QtWidgets.QPushButton(self.fm_botones)
        self.btn9.setGeometry(QtCore.QRect(240, 20, 88, 51))
        self.btn9.setStyleSheet("background-color: rgb(28, 113, 216);\n"
"color: rgb(246, 245, 244);\n"
"")
        self.btn9.setObjectName("btn9")
        self.btn4 = QtWidgets.QPushButton(self.fm_botones)
        self.btn4.setGeometry(QtCore.QRect(20, 110, 88, 51))
        self.btn4.setStyleSheet("background-color: rgb(28, 113, 216);\n"
"color: rgb(246, 245, 244);\n"
"")
        self.btn4.setObjectName("btn4")
        self.btnIgual = QtWidgets.QPushButton(self.fm_botones)
        self.btnIgual.setGeometry(QtCore.QRect(240, 280, 88, 51))
        self.btnIgual.setStyleSheet("background-color: rgb(28, 113, 216);\n"
"color: rgb(246, 245, 244);\n"
"")
        self.btnIgual.setObjectName("btnIgual")
        self.btn1 = QtWidgets.QPushButton(self.fm_botones)
        self.btn1.setGeometry(QtCore.QRect(20, 200, 88, 51))
        self.btn1.setStyleSheet("background-color: rgb(28, 113, 216);\n"
"color: rgb(246, 245, 244);\n"
"")
        self.btn1.setObjectName("btn1")
        self.btn6 = QtWidgets.QPushButton(self.fm_botones)
        self.btn6.setGeometry(QtCore.QRect(240, 110, 88, 51))
        self.btn6.setStyleSheet("background-color: rgb(28, 113, 216);\n"
"color: rgb(246, 245, 244);\n"
"")
        self.btn6.setObjectName("btn6")
        self.btnMult = QtWidgets.QPushButton(self.fm_botones)
        self.btnMult.setGeometry(QtCore.QRect(350, 200, 88, 51))
        self.btnMult.setStyleSheet("background-color: rgb(224, 27, 36);")
        self.btnMult.setObjectName("btnMult")
        self.btn0 = QtWidgets.QPushButton(self.fm_botones)
        self.btn0.setGeometry(QtCore.QRect(130, 280, 88, 51))
        self.btn0.setStyleSheet("background-color: rgb(28, 113, 216);\n"
"color: rgb(246, 245, 244);\n"
"\n"
"")
        self.btn0.setObjectName("btn0")
        self.btnSum = QtWidgets.QPushButton(self.fm_botones)
        self.btnSum.setGeometry(QtCore.QRect(350, 20, 90, 51))
        self.btnSum.setStyleSheet("background-color: rgb(224, 27, 36);")
        self.btnSum.setObjectName("btnSum")
        self.btn3 = QtWidgets.QPushButton(self.fm_botones)
        self.btn3.setGeometry(QtCore.QRect(240, 200, 88, 51))
        self.btn3.setStyleSheet("background-color: rgb(28, 113, 216);\n"
"color: rgb(246, 245, 244);\n"
"")
        self.btn3.setObjectName("btn3")
        self.btn7 = QtWidgets.QPushButton(self.fm_botones)
        self.btn7.setGeometry(QtCore.QRect(20, 20, 88, 51))
        self.btn7.setStyleSheet("background-color: rgb(28, 113, 216);\n"
"color: rgb(246, 245, 244);\n"
"")
        self.btn7.setObjectName("btn7")
        self.btn8 = QtWidgets.QPushButton(self.fm_botones)
        self.btn8.setGeometry(QtCore.QRect(130, 20, 88, 51))
        self.btn8.setStyleSheet("background-color: rgb(28, 113, 216);\n"
"color: rgb(246, 245, 244);\n"
"\n"
"")
        self.btn8.setObjectName("btn8")
        self.btnRes = QtWidgets.QPushButton(self.fm_botones)
        self.btnRes.setGeometry(QtCore.QRect(350, 110, 90, 51))
        self.btnRes.setStyleSheet("background-color: rgb(224, 27, 36);")
        self.btnRes.setObjectName("btnRes")
        self.btn5 = QtWidgets.QPushButton(self.fm_botones)
        self.btn5.setGeometry(QtCore.QRect(130, 110, 88, 51))
        self.btn5.setStyleSheet("background-color: rgb(28, 113, 216);\n"
"color: rgb(246, 245, 244);\n"
"\n"
"")
        self.btn5.setObjectName("btn5")
        self.btnAPAR = QtWidgets.QPushButton(self.fm_botones)
        self.btnAPAR.setGeometry(QtCore.QRect(460, 20, 88, 51))
        self.btnAPAR.setStyleSheet("background-color: rgb(255, 120, 0);")
        self.btnAPAR.setObjectName("btnAPAR")
        self.btnCPAR = QtWidgets.QPushButton(self.fm_botones)
        self.btnCPAR.setGeometry(QtCore.QRect(460, 110, 88, 51))
        self.btnCPAR.setStyleSheet("background-color: rgb(255, 120, 0);")
        self.btnCPAR.setObjectName("btnCPAR")
        self.btnLimpiar = QtWidgets.QPushButton(self.fm_botones)
        self.btnLimpiar.setGeometry(QtCore.QRect(460, 200, 88, 51))
        self.btnLimpiar.setStyleSheet("background-color: rgb(255, 120, 0);")
        self.btnLimpiar.setObjectName("btnLimpiar")
        self.btnDecimal = QtWidgets.QPushButton(self.fm_botones)
        self.btnDecimal.setGeometry(QtCore.QRect(20, 280, 88, 51))
        self.btnDecimal.setStyleSheet("background-color: rgb(145, 65, 172);\n"
"color: rgb(246, 245, 244);\n"
"\n"
"")
        self.btnDecimal.setObjectName("btnDecimal")
        self.lcdEntrada = QtWidgets.QLCDNumber(self.frame)
        self.lcdEntrada.setGeometry(QtCore.QRect(20, 10, 561, 71))
        self.lcdEntrada.setToolTip("")
        self.lcdEntrada.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.lcdEntrada.setAutoFillBackground(False)
        self.lcdEntrada.setStyleSheet("background-color: rgb(46, 194, 126);\n"
"color: rgb(246, 245, 244);\n"
"")
        self.lcdEntrada.setInputMethodHints(QtCore.Qt.ImhHiddenText)
        self.lcdEntrada.setProperty("value", 12.0)
        self.lcdEntrada.setProperty("intValue", 12)
        self.lcdEntrada.setObjectName("lcdEntrada")
        self.lblEntrada = QtWidgets.QLabel(self.frame)
        self.lblEntrada.setGeometry(QtCore.QRect(20, 90, 551, 51))
        self.lblEntrada.setStyleSheet("font: 87 18pt \"Noto Kufi Arabic\";\n"
"color:\"green\";")
        self.lblEntrada.setObjectName("lblEntrada")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(610, 40, 131, 511))
        self.frame_2.setStyleSheet("background-color: rgb(61, 56, 70);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.pushButton = QtWidgets.QPushButton(self.frame_2)
        self.pushButton.setGeometry(QtCore.QRect(10, 30, 111, 27))
        self.pushButton.setStyleSheet("background-color: rgb(51, 209, 122);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 70, 111, 27))
        self.pushButton_2.setStyleSheet("background-color: rgb(255, 120, 0);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 801, 601))
        self.label.setStyleSheet("background-image: url(:/cct/background.jpg);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label.raise_()
        self.frame.raise_()
        self.frame_2.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calculadora"))
        self.btnDiv.setText(_translate("MainWindow", "/"))
        self.btnPot.setText(_translate("MainWindow", "^"))
        self.btn2.setText(_translate("MainWindow", "2"))
        self.btn9.setText(_translate("MainWindow", "9"))
        self.btn4.setText(_translate("MainWindow", "4"))
        self.btnIgual.setText(_translate("MainWindow", "="))
        self.btn1.setText(_translate("MainWindow", "1"))
        self.btn6.setText(_translate("MainWindow", "6"))
        self.btnMult.setText(_translate("MainWindow", "*"))
        self.btn0.setText(_translate("MainWindow", "0"))
        self.btnSum.setText(_translate("MainWindow", "+"))
        self.btn3.setText(_translate("MainWindow", "3"))
        self.btn7.setText(_translate("MainWindow", "7"))
        self.btn8.setText(_translate("MainWindow", "8"))
        self.btnRes.setText(_translate("MainWindow", "-"))
        self.btn5.setText(_translate("MainWindow", "5"))
        self.btnAPAR.setText(_translate("MainWindow", "("))
        self.btnCPAR.setText(_translate("MainWindow", ")"))
        self.btnLimpiar.setText(_translate("MainWindow", "Limpiar"))
        self.btnDecimal.setText(_translate("MainWindow", "."))
        self.lblEntrada.setText(_translate("MainWindow", "12+0"))
        self.pushButton.setText(_translate("MainWindow", "Cargar Archivo"))
        self.pushButton_2.setText(_translate("MainWindow", "Ver salida"))

