# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_Menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(664, 444)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnAcercaDe = QtWidgets.QPushButton(self.centralwidget)
        self.btnAcercaDe.setGeometry(QtCore.QRect(220, 200, 271, 51))
        self.btnAcercaDe.setStyleSheet("QPushButton {\n"
"    background-color:\"#49B4BD\";\n"
"    color:white;\n"
"    border-radius:25px\n"
"}\n"
"QPushButton:hover { \n"
"    color: white;\n"
"    background-color:  \"#B1DC3D\";\n"
"}")
        self.btnAcercaDe.setObjectName("btnAcercaDe")
        self.btnCalculadora = QtWidgets.QPushButton(self.centralwidget)
        self.btnCalculadora.setGeometry(QtCore.QRect(220, 100, 271, 51))
        self.btnCalculadora.setStyleSheet("QPushButton {\n"
"    background-color:\"#49B4BD\";\n"
"    color:white;\n"
"    border-radius:25px\n"
"}\n"
"QPushButton:hover { \n"
"    color: white;\n"
"    background-color:  \"#B1DC3D\";\n"
"}")
        self.btnCalculadora.setObjectName("btnCalculadora")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 671, 451))
        self.label.setStyleSheet("background-image: url(:/cct/background.jpg);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 30, 571, 391))
        self.label_2.setStyleSheet("background-color: rgba(0, 0, 0, 100);\n"
"border-radius:25px;")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(150, 100, 61, 51))
        self.label_3.setStyleSheet("image: url(:/cct/calculator.png);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(150, 200, 61, 51))
        self.label_4.setStyleSheet("image: url(:/cct/about.png);")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.btnSalir = QtWidgets.QPushButton(self.centralwidget)
        self.btnSalir.setGeometry(QtCore.QRect(220, 290, 271, 51))
        self.btnSalir.setStyleSheet("QPushButton {\n"
"    background-color:\"#D5600F\";\n"
"    border-radius:25px\n"
"}\n"
"QPushButton:hover { \n"
"    color: white;\n"
"    background-color:  \"#E13610\";\n"
"}")
        self.btnSalir.setObjectName("btnSalir")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(150, 290, 61, 51))
        self.label_5.setStyleSheet("image: url(:/cct/exit.png);")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label.raise_()
        self.label_2.raise_()
        self.btnCalculadora.raise_()
        self.btnAcercaDe.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.btnSalir.raise_()
        self.label_5.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Menú"))
        self.btnAcercaDe.setText(_translate("MainWindow", "Acerca De"))
        self.btnCalculadora.setText(_translate("MainWindow", "Calculadora"))
        self.btnSalir.setText(_translate("MainWindow", "Salir"))
