# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_AcercaDe.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(806, 490)
        MainWindow.setStyleSheet("background-color: rgb(16, 14, 55);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 811, 471))
        self.label.setStyleSheet("background-image: url(:/cct/background_3.jpg);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 10, 711, 471))
        self.label_2.setStyleSheet("background-color: rgba(0, 0, 0, 204);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(320, 0, 181, 151))
        self.label_3.setStyleSheet("image: url(:/cct/logo.png);\n"
"background-color: \"transparent\";")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(210, 140, 381, 20))
        self.label_4.setStyleSheet("background-color: \"transparent\";\n"
"font: 75 11pt \"dsrom10\";\n"
"color:\"white\";")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(320, 170, 171, 20))
        self.label_5.setStyleSheet("background-color: \"transparent\";\n"
"color: rgb(26, 95, 180);")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(300, 200, 221, 19))
        self.label_6.setStyleSheet("background-color: \"transparent\";\n"
"color: rgb(26, 95, 180);")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(290, 250, 221, 19))
        self.label_7.setStyleSheet("background-color: \"transparent\";\n"
"color: rgb(26, 95, 180);")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(320, 290, 151, 19))
        self.label_8.setStyleSheet("background-color: \"transparent\";\n"
"color: rgb(26, 95, 180);")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(70, 380, 321, 19))
        self.label_9.setStyleSheet("background-color: \"transparent\";\n"
"color: rgb(87, 227, 137);")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(420, 350, 341, 19))
        self.label_10.setStyleSheet("background-color: \"transparent\";\n"
"color: rgb(87, 227, 137);")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(70, 410, 321, 19))
        self.label_11.setStyleSheet("background-color: \"transparent\";\n"
"color: rgb(87, 227, 137);")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(70, 320, 321, 19))
        self.label_12.setStyleSheet("background-color: \"transparent\";\n"
"color: rgb(87, 227, 137);")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(420, 380, 341, 19))
        self.label_13.setStyleSheet("background-color: \"transparent\";\n"
"color: rgb(87, 227, 137);")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(70, 350, 321, 19))
        self.label_14.setStyleSheet("background-color: \"transparent\";\n"
"color: rgb(87, 227, 137);\n"
"")
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(430, 320, 321, 19))
        self.label_15.setStyleSheet("background-color: \"transparent\";\n"
"color: rgb(87, 227, 137);")
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(340, 440, 131, 19))
        self.label_16.setStyleSheet("background-color: \"transparent\";\n"
"font: 75 italic 11pt \"FontAwesome\";\n"
"color:\"white\";")
        self.label_16.setObjectName("label_16")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(290, 220, 241, 30))
        self.label_18.setStyleSheet("background-color: \"transparent\";\n"
"color: rgb(192, 191, 188);")
        self.label_18.setObjectName("label_18")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Acerca De"))
        self.label_4.setText(_translate("MainWindow", "Universidad Nacional Autónoma De Honduras"))
        self.label_5.setText(_translate("MainWindow", "Ingeniería en sistemas"))
        self.label_6.setText(_translate("MainWindow", "IS-913 Diseño de compiladores"))
        self.label_7.setText(_translate("MainWindow", "Proyecto Final: Traductor Básico"))
        self.label_8.setText(_translate("MainWindow", "Integrantes de grupo:"))
        self.label_9.setText(_translate("MainWindow", "Gertrudiz Julissa Anariba Zavala 20151900003"))
        self.label_10.setText(_translate("MainWindow", "Yensy Gabriela Velásquez Aguiluz 20151900052"))
        self.label_11.setText(_translate("MainWindow", "Jese Daniel Aguilar Martinez 20141012902"))
        self.label_12.setText(_translate("MainWindow", "Amilcar Antonio Rodriguez Velasquez 20172500133"))
        self.label_13.setText(_translate("MainWindow", "Yesenia Xiomara Espinoza Blandin 20101006208"))
        self.label_14.setText(_translate("MainWindow", "Deiby Benigno López Ramírez 20151030486"))
        self.label_15.setText(_translate("MainWindow", "Laura Karina Chinchilla Chinchilla 20152100165"))
        self.label_16.setText(_translate("MainWindow", "III-PAC 2021"))
        self.label_18.setText(_translate("MainWindow", "Ing. Alex Hernán Moncada Gómez"))

